name: Deploy Github Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: ["Update Data"]
    types: [completed]
jobs:
  # Build job
  build:
    name: Build Project
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        uses: ./.github/composite-actions/setup
      - name: Build
        env:
          PUBLIC_ENV__BASE_URL: /the-sorter
          PUBLIC_ENV__RANKINGS_API_URL: ${{ vars.RANKINGS_API_URL }}
        run: bun run ci:build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/client

    # <Not provided for brevity>
    # At a minimum this job should upload artifacts using actions/upload-pages-artifact

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step

    outputs:
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
